In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[5,6,7],[8,9,10]])
c=a+b
type(c)
c.shape

(2, 3)

In [3]:
A = "안녕하세요 지금은 데이터 전처리 수업 시간입니다"
A[0]

'안'

In [4]:
# 문장전체가 출력됨
A[:]

'안녕하세요 지금은 데이터 전처리 수업 시간입니다'

In [7]:
A[0:4]

'안녕하세'

In [9]:
A[10:13]

'데이터'

In [10]:
A[-1]

'다'

In [11]:
A[-5:]

'시간입니다'

In [13]:
# 포멧 변경
print(("I am a {}").format("boy"))

I am a boy


In [15]:
# replace 함수
url = "https://www.youtube.com/"
str = url.replace("https://","")
str

'www.youtube.com/'

In [16]:
A = [10,20,30,40,50,60,70,80,90]
A[0] + A[5] 

70

In [18]:
A = ["독고영재, 50", "김철수, 30"]
# A = "안녕하세요 지금은 데이터 전처리 수업 시간입니다."
A[0]

'독고영재, 50'

In [19]:
A[0][0:4]

'독고영재'

In [27]:
# 이거 좀 중요할 듯 ?
a = ["독고영재, 50", "김철수, 30"]
b = ["김철수","20","김영희,25"]

a[0][:a[0].index(",")]
# b[0][:b[1].index(",")]

'독고영재'

In [28]:
# 리스트에 값 추가
a=["hi",10,"80","김철수",50,50.6]
a.append(1)
a


['hi', 10, '80', '김철수', 50, 50.6, 1]

In [29]:
# 제거할 위치를 선택하고 삭제
a.pop(1)
a

['hi', '80', '김철수', 50, 50.6, 1]

In [30]:
b = a.index(50)
a.pop(b)
a

['hi', '80', '김철수', 50.6, 1]

In [34]:
# append 함수 뒤에 넣고 싶은 값을 넣는다
a = np.array([1,2,3,4])
a = np.append(a,[4,5])
a

array([1, 2, 3, 4, 4, 5])

In [33]:
# insert 함수 넣고 싶은 위치에 넣기
a = np.insert(a, 1, [7,8])
a

array([1, 7, 8, 7, 8, 2, 3, 4, 4, 5])

In [36]:
# delete 함수 지우고 싶은 위치를 전달
a = np.array([1,2,3,4])
a = np.delete(a, [0])
a

array([2, 3, 4])

In [37]:
# 배열 수직으로 합치기
array1=np.array([[1,2,3],[4,5,6]])
b=np.array([[5,6,7],[8,9,10]])

In [39]:
# 딕셔너리 키 값 안에 변수를 넣는 방식
A = {1: "김철수", 2: "박영희"}
A[1]
A.get(2)

'박영희'

In [40]:
# 딕셔너리 추가 삭제
A = {"1-A": "김철수", "20-B": "박영희"}
A["2-A"] = "이혜준" # 추가
A

{'1-A': '김철수', '20-B': '박영희', '2-A': '이혜준'}