In [1]:
a = 20
b =30
print(a+b)

50


In [58]:
name = "이혜준"
print("결과: 안녕하세요 {}님 데이터전처리 수업에 오신것을 환영합니다.".format(name))

결과: 안녕하세요 이혜준님 데이터전처리 수업에 오신것을 환영합니다.


In [29]:
import numpy as np
list = [1,5,5,7,3,6,88,12,5,74,4,8,64,2,7,89,33,1,6,8,1,5,6,7]
type(list)


list

In [10]:
array_1 = np.array([1,5,5,7,3,6,88,12,5,74,4,8,64,2,7,89,33,1,6,8,1,5,6,7])
type(array_1)

numpy.ndarray

In [60]:
print(array_1[0:5])
print(array_1[5:10])
print(array_1[0:5] + array_1[5:10])

[1 5 5 7 3]
[ 6 88 12  5 74]
[ 7 93 17 12 77]


In [30]:
list.index(88)

6

In [52]:
name = ["Jone -30", "Park-30", "Kim-20", "Lee-10", "Oh-32", "Kang-25"]
#print(name[name.index("Lee-10"):name.index("Oh-32")])
print("결과1:{}".format(name[3][:name[3].index("-")]))

결과1:Lee


In [68]:
list = ["데이터 전처리 수업, 입니다.", "Data Preprocessing"]
list.pop(0)
list.append("데이터 전처리 수업 입니다")

list.pop(0)
list.append("Data preprocesing")
print("결과1: {}".format(list[0]))
print("결과2: {}".format(list[1]))

결과1: 데이터 전처리 수업 입니다
결과2: Data preprocesing
